name: Feature Request
description: Suggest a new feature or enhancement for Quark
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What are you trying to achieve?
      placeholder: I'm trying to... but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this to work
      placeholder: I would like Quark to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: Show us how you'd like to use this feature
      render: python
      placeholder: |
        from models.transformer import Transformer, TransformerConfig

        # Example of how the feature would be used
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, references to papers, implementations in other frameworks, etc.
      placeholder: Related papers, implementations, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
